### ISSUE TITLE
Query in technology support

### ISSUE THREAD

**Issue by naga1992** [Ginger-Automation/Ginger#131]
does ginger support in automating sap fiori applications.

**Comment by yaronweiss** [comment]
Sorry for the late response, 
Ginger is leveraging on Selenium for Web automation and Appium for mobile automation, whatever is possible to do with Selenium and Appium will be possible to do with Ginger just much easier.
from my short experience with SAP Fiori one of the challenges is taking screen shots or video since the application goes into secured/protected mode which doesn't enable it.
if you have public application we can give it a try and let you know how it goes.
Have you tried automating using Selenium/Appium?

**Comment by naga1992** [comment]
thanks for the answer, yes have tried automating using selenium , but we are not able to identify objects which are present within the fiori app
