### ISSUE TITLE
Allow Custom Folder Names for Run Set Report Folder

### ISSUE THREAD

**Issue by kharithomas** [Ginger-Automation/Ginger#2429]
**Is your feature request related to a problem? Please describe.**

When executing a run set in Ginger, the post execution action _Generate Report_ will create a folder with a unique string appended to the name of the run set `BBTR_REGRESSION_XXXXXXXXXX`. Instead of a random unique string, it would be nice to allow a variable to be passed here to be used as the folder name. 

![0](https://user-images.githubusercontent.com/55037984/168680644-5615ec9e-52b2-47f5-a003-c0ee20435cc2.png)

In my specific case, I work on automation as part of Amdocs' QE automation development team and we often use run sets to generate reports for progression and regression testing. Unfortunately, when the time comes to view the reports it's very difficult to identify which folder contains the execution report that we need so we end up having to open the folders one-by-one to see the report contents.

**Describe the solution you'd like**

When configuring the post execution run set action, add another input field to allow the user to edit the name that will be used to create the folder. _Bonus: Allow this input field to have the Value Expression editor so variables can be passed in._ Once the run set finishes execution, the folder containing the execution report will be the name defined in the Design settings.

![Group 7](https://user-images.githubusercontent.com/55037984/168682946-2ea9029d-34e1-4f78-a6d6-bb52d2dcebdc.png)

**Describe alternatives you've considered**

We've tried to use python to edit the folder with a custom name after each run set execution but this solution feels disjointed and could possibly be better handled by the Ginger UI itself as a setting in the post execution Details tab.

**Additional context**

None.

**Comment by digvijayAMDX** [comment]
Even if we provide some variable to be used as folder name, it will have to contain some separate characters to be differentiated from each runs of the same executions otherwise, it will fail to create folder with exactly the same name all the times.
You can use option of having same folder always to be updated for every run of the runset and have only single report at any given time, by Selecting the option of "**Keep single report folder for all Run Set executions**" given in the screenshot you have attached.

**Comment by kharithomas** [comment]
@digvijayAMDX Please close this ticket - thanks.
