### ISSUE TITLE
Dynamic xpath not working when value fetch from DB or Global Variable

### ISSUE THREAD

**Issue by Sunny-Teo** [Ginger-Automation/Ginger#958]
I am trying to make the xpath dynamic. So, in POM, I have made an extra copy of the xpath and made it dynamic by passing a variable which is coming from DB. In the value expression editor the correct value is displayed but when you try to test it then it will fail saying incorrect xpath.

![Value Expression Editor](https://user-images.githubusercontent.com/25932794/58616235-c9b3dc80-82da-11e9-9afd-d24e711c0841.PNG)
![Dynamic Xpath issue](https://user-images.githubusercontent.com/25932794/58616240-ccaecd00-82da-11e9-80de-9e47ff8653ba.PNG)

Same issue if used global parameters.
How to achieve dynamic xpath in POM?

Ginger Version 3.1

**Comment by MeniKadosh1** [comment]
That should work.
Prateek- please raise Bug for it and check.

**Comment by vyasprateek** [comment]
The Issue was fixed in [Ginger v3.3](https://github.com/Ginger-Automation/Ginger/releases/download/v3.3-Official/Ginger.3.3.0.0.exe). Please update to the latest [Ginger v3.5](https://github.com/Ginger-Automation/Ginger/releases/download/v3.5-Official/Ginger.3.5.0.0.exe) for more additional features and functionalities.
